### ISSUE TITLE
Main container fails to communicate with chromedriver container

### ISSUE THREAD

**Issue by jupjohn** [PussTheCat-org/docker-proxitok-quay#3]
Went to run this yesterday on two separate hosts using docker compose. Application starts up and runs, but when a URL is hit the main container complains that it can't locate the chromedriver host.

I'll drop some logs in an hour or so. My guess is that the inter-container resolution isn't working - probably due to a chromedriver image change.

**Comment by TheFrenchGhosty** [comment]
I dug into it: ProxiTok connects to the chrome container correctly, however, for whatever reason, ChromeDriver is refusing connection. This wasn't the case before, so something definitely changed.

```
Starting ChromeDriver 100.0.4896.60 (6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}) on port 9515
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1649768250.825][SEVERE]: Unable find match for host: proxitok-chrome:9515
[1649768266.554][SEVERE]: Unable find match for host: proxitok-chrome:9515
```

I have no idea why, since I never used ChromeDriver

@pablouser1 Any idea?

Edit:

Adding: `hostname: proxitok-chrome` to the chrome container seems to solve the `Unable find match for host: proxitok-chrome:9515` however, ProxiTok refuses to load anything now.

**Comment by TheFrenchGhosty** [comment]
Follow up issue: https://github.com/pablouser1/ProxiTok/issues/26

**Comment by jupjohn** [comment]
Thanks for the investigation/fix and sorry for not getting any logs out. Appreciated!
